title: Onedots
email: onedots0@outlook.com
description: "记录分享学习和生活"
baseurl: ""  # Change this if you're using a subpath
url: ""      # Set this to your site's full URL when live
github_username: onedots1014

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll/collection

# Excluded items (optional, for reference only)
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Custom collections
collections:
  columns:
    output: true
    permalink: /columns/:path/
    
defaults:
  - scope:
      path: "_columns"
      type: columns
    values:
      layout: column
